### ISSUE TITLE
Record and document prototype 0

### ISSUE THREAD

**Issue by jonjhiggins** [uwe-xr-ma-2023/mr-handtracking-prototype#21]
A/C 

- Video: showing casted headset experience and experience from external view. Shows hand tracking post triggering sound. Example video showing internal/external experience: https://youtu.be/eu_sqkEGW2I
- Text: document, why, what happened/challenges/learnings

**Comment by Ajiun1010** [comment]
**Video:** Participants executes the thumbs up pose in play mode; 1 thumb, 2 Thumbs 

**Why:** Pose recognition to trigger sound

**What Happened:** 

1. Intro sound executed sound at the beginning of the experience
2. Pop sound successfully executed on thumbs up pose

**Challenges**
1. Pose tolerance is too high
2. Sound recognition is activated by knuckles and metatarsals
3. Sound recognition on one hand at a time, no double or second pops.
